### ISSUE TITLE
textbox should be resizable to smaller sizes

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#60]
Currently the textbook can't be resized to any shorter than in this screenshot:
![2017-08-12-12 51 29_001](https://user-images.githubusercontent.com/963849/29242574-90660034-7f5d-11e7-9dfa-c144e7d6b1b0.png)

**Comment by ftyers** [comment]
This was fixed a while ago, not sure which commit. It now auto resizes based on how long the sentence is.

**Comment by jonorthwash** [comment]
Auto-resizing aside, it still doesn't allow the user to have any input into its size.  For example, in the attached screenshot, I can't make it go any smaller.

![2017-11-03-12 16 38_001](https://user-images.githubusercontent.com/963849/32384329-f3365f28-c090-11e7-8105-267f705832ea.png)

This is in Chromium 60.0.3112.78.

**Comment by ftyers** [comment]
Yes you can. Look at the bottom right hand corner. There is the normal way of resizing text boxes.

![captura de 2017-11-03 18-27-13](https://user-images.githubusercontent.com/449545/32387399-a17b1a1e-c0c4-11e7-955e-31bc7207f962.png)

**Comment by jonorthwash** [comment]
I'm telling you, it doesn't let me make it smaller at that point—just bigger.

**Comment by ftyers** [comment]
As you can see, it lets me, so maybe you have some misconfiguration ?

**Comment by jonorthwash** [comment]
Seems to work in firefox.  I'll try upgrading chromium....

**Comment by jonorthwash** [comment]
Yeah, works now, on 61.0.3163.100.

So I guess we're not supporting anything older than this version of chrome/chromium?

**Comment by jonorthwash** [comment]
> This was fixed a while ago, not sure which commit.

That's because you're not tracking chromium commits :-P

**Comment by ftyers** [comment]
@jonorthwash LOL

Also, I'm well known for running terribly out of date software, so I think that if anyone wants to run anything older than what's in Debian... well, they can file a bug :D

**Comment by jonorthwash** [comment]
> Also, I'm well known for running terribly out of date software,

In this case, you were running the latest version in Debian unstable, which many people will not be...
